version: '3.8'

services:
  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./config:/config
    networks:
      - camnet

  nginx:
    image: nginx:stable
    container_name: go2rtc-nginx
    restart: unless-stopped
    depends_on:
      - go2rtc
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./go2rtc.htpasswd:/etc/nginx/go2rtc.htpasswd:ro
    ports:
      - "1984:80"
    networks:
      - camnet

networks:
  camnet:
    driver: bridge
